### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by robertdubineinsteinmed** [JiekaiLab/scTE#103]
We installed scTE with python3.9 and I have successfully run scTE_build for mm10. 
However I am having issues running scTE. The issue appears to be 
TypeError: unsupported operand type(s) for |: 'type' and 'type'
(see at bottom for entire printout).

This  issue appears both when I attempt to run my own 10X genomics file using

scTE -i ${BAM_FILE} -o ${prefixFilename} -x ${mm10_sc_index} -CB CB -UMI UB

and it also appears when I run the test.bam provided with the code:

scTE -i test.bam -o secondTest -x test.exclusive.idx -CB CR -UMI UR

I have examined the numerous github issues listed for scTE and is seems as though others have indicated that python 3.9 should be OK for this software. Can you provide some help or suggestion?
Thanks,
Rob

Output from the failed run is:

/public/apps/conda3/bin/scTE:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
Traceback (most recent call last):
  File "/public/apps/conda3/bin/scTE", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
  File "/public/apps/conda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public/apps/conda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1561, in run_script
    exec(code, namespace, namespace)
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/scTE-1.0-py3.9.egg/EGG-INFO/scripts/scTE", line 13, in <module>
    from scTE.base import *
  File "/public/apps/conda3/lib/python3.9/site-packages/scTE-1.0-py3.9.egg/scTE/base.py", line 16, in <module>
    import anndata as ad
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/__init__.py", line 29, in <module>
    from ._core.anndata import AnnData
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/_core/anndata.py", line 25, in <module>
    from .. import utils
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/utils.py", line 15, in <module>
    from ._core.sparse_dataset import BaseCompressedSparseDataset
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/_core/sparse_dataset.py", line 30, in <module>
    from .._settings import settings
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/_settings.py", line 17, in <module>
    from anndata.compat import CAN_USE_SPARSE_ARRAY
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/compat/__init__.py", line 49, in <module>
    Index1D = slice | int | str | np.int64 | np.ndarray
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by robertdubineinsteinmed** [comment]
I also note the same issue when I run scTE --help or scTE -h as seen below. Clearly there is some install issue. We're using python 3.9. Can you suggest what might be wrong with our installation? 
Thanks,
robert

scTE -h
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
Traceback (most recent call last):
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/bin/scTE", line 13, in <module>
    from scTE.base import *
  File "/public/apps/conda3/lib/python3.9/site-packages/scTE/base.py", line 16, in <module>
    import anndata as ad
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/__init__.py", line 29, in <module>
    from ._core.anndata import AnnData
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/_core/anndata.py", line 25, in <module>
    from .. import utils
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/utils.py", line 15, in <module>
    from ._core.sparse_dataset import BaseCompressedSparseDataset
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/_core/sparse_dataset.py", line 30, in <module>
    from .._settings import settings
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/_settings.py", line 17, in <module>
    from anndata.compat import CAN_USE_SPARSE_ARRAY
  File "/public/apps/conda3/lib/python3.9/site-packages/anndata-0.11.0rc3-py3.9.egg/anndata/compat/__init__.py", line 49, in <module>
    Index1D = slice | int | str | np.int64 | np.ndarray
TypeError: unsupported operand type(s) for |: 'type' and 'type'
