### ISSUE TITLE
Error when running scTEATAC

### ISSUE THREAD

**Issue by cnk113** [JiekaiLab/scTE#11]
Hello,

I'm trying to run this on my scATAC-seq sample and I'm running into this issue:
```TypeError: Readanno() got an unexpected keyword argument 'genome'``
I built the hg38 index using the same method you did with you mm10 genome on the README.
scTEATAC -i filtered.bam -x hg38.te.atac.idx -p 16 -CB -g hg38
Any ideas why this is an issue?

Thanks,
Chang

**Comment by leeyoyohku** [comment]
I remember the updated scTE doesn't need genome flag. Perhaps try without '--genome hg38'?

**Comment by cnk113** [comment]
So when I do it without it, I get
```
scTE_scatacseq: error: the following arguments are required: -g/--genome
```

**Comment by leeyoyohku** [comment]
Oh, I see it. It's because you put` -g hg38 `after -CB flag. You should specify CR,CB, or False after -CB.

**Comment by cnk113** [comment]
I'm back to the original error now:
```
File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/scTE-1.0-py3.7.egg/EGG-INFO/scripts/scTEATAC", line 216, in <module>
    main()
  File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/scTE-1.0-py3.7.egg/EGG-INFO/scripts/scTEATAC", line 144, in main
    allelement, chr_list, all_annot, glannot = Readanno(filename=outname, annoglb=args.annoglb[0], genome=args.genome)
TypeError: Readanno() got an unexpected keyword argument 'genome'
```

**Comment by cnk113** [comment]
I just fixed this by commenting out the genome parameter in the line of Readanno.

**Comment by funpys** [comment]
@cnk113 
Thank you.
I had the same issue.
And I fixed it in the same way.

**Comment by funpys** [comment]
I got another error.

INFO    : Calculating expression... 2021-07-30 08:06:59
Traceback (most recent call last):
  File "/home/bskim/anaconda3/bin/scTEATAC", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTEATAC')
  File "/home/bskim/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bskim/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/bskim/anaconda3/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTEATAC", line 216, in <module>
    main()
  File "/home/bskim/anaconda3/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTEATAC", line 198, in main
    len_res, genenumber, filename = Countexpression(filename=args.out, allelement=allelement, genenumber=args.genenumber, cellnumber=args.cellnumber,hdf5=args.hdf5)
  File "/home/bskim/anaconda3/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/scTE/base.py", line 505, in Countexpression
    adata = ad.AnnData(np.asarray(data),var = var,obs = obs)
  File "/home/bskim/anaconda3/lib/python3.8/site-packages/anndata-0.7.6-py3.8.egg/anndata/_core/anndata.py", line 308, in __init__
    self._init_as_actual(
  File "/home/bskim/anaconda3/lib/python3.8/site-packages/anndata-0.7.6-py3.8.egg/anndata/_core/anndata.py", line 463, in _init_as_actual
    _check_2d_shape(X)
  File "/home/bskim/anaconda3/lib/python3.8/site-packages/anndata-0.7.6-py3.8.egg/anndata/_core/anndata.py", line 97, in _check_2d_shape
    raise ValueError(
ValueError: X needs to be 2-dimensional, not 1-dimensional.

**Comment by ApolloWuu** [comment]
Hi,

Have you fixed the Readanno error? I was wondering how to fix it.

Best,
Apollo

**Comment by funpys** [comment]
I couldn't fix it.
I just analyzed the data by Signac with TE annotation file.

**Comment by sabrinacamp2** [comment]
@funpys How did you use the TE annotation file in Signac? And did you calculate counts over TEs using the GeneActivity function? I'm also looking for a workaround here!

**Comment by funpys** [comment]
@sabrinacamp2 No. I just checked whether region of interest in scATAC data is TE or not.
