### ISSUE TITLE
Error Creating Custom reference for genome

### ISSUE THREAD

**Issue by ivanferrreira** [JiekaiLab/scTE#15]
Hi Jiekai Lab - thank you for developing such great resouce!

I keep on having an issue to create custom genomes for scRNA analysis. Even when I run the example data with:
scTE_build -te ./Data/TE.bed -gene ./Data/Gene.gtf -o test.idx

I get the error: "Counting genome other not supported"

Could you please help me? I've ruled out installation issues as I don't have any other problems in reproducing the other parts of your pipeline (e.g., with scATAC or built in genomes)

Thank you

Ivan Ferreira
Sauka-Spengler Lab

**Comment by jphe** [comment]
Hi Ivan,

We have update the scTE and should be fixed now, can you try again with the newest version.

Jphe

**Comment by ivanferrreira** [comment]
Hi Jphe, thank you for getting back to me so quickly, very appreciated

Do you mind sending me instructions on how to update to the newest version?

Ivan

________________________________

**Comment by jphe** [comment]
Just remove the old one, and then reinstall it.

```
git clone https://github.com/JiekaiLab/scTE.git
cd scTE
python setup.py install
```

**Comment by ivanferrreira** [comment]
Thank you

I just finished removing the old one and reinstalling - it seems something is still a bit off with the scTE_build function, but not the others

I am now gettting the following error message now with the test data:


INFO    : Building the scTE genome annotation index... 2021-05-27 09:45:52

/gpfs3/well/combat/users/akt326/devel/ivybridge/python3-venv-ivybridge-3.8.2/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTE_build:110: DeprecationWarning: 'U' mode is deprecated

  o = open(tefile,'rU')

Traceback (most recent call last):

  File "/well/combat/users/akt326/devel/ivybridge/python3-venv-ivybridge-3.8.2/bin/scTE_build", line 4, in <module>

    __import__('pkg_resources').run_script('scTE==1.0', 'scTE_build')

  File "/well/combat/users/akt326/devel/ivybridge/python3-venv-ivybridge-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script

    self.require(requires)[0].run_script(script_name, ns)

  File "/well/combat/users/akt326/devel/ivybridge/python3-venv-ivybridge-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1462, in run_script

    exec(code, namespace, namespace)

  File "/gpfs3/well/combat/users/akt326/devel/ivybridge/python3-venv-ivybridge-3.8.2/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTE_build", line 468, in <module>

    main()

  File "/gpfs3/well/combat/users/akt326/devel/ivybridge/python3-venv-ivybridge-3.8.2/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTE_build", line 461, in main

    genomeIndex(args.genome,args.mode,tefile,genefile, args.out,'No path','No path')

  File "/gpfs3/well/combat/users/akt326/devel/ivybridge/python3-venv-ivybridge-3.8.2/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTE_build", line 127, in genomeIndex

    gls.load_list(clean)

  File "/well/combat/users/akt326/devel/ivybridge/python3-venv-ivybridge-3.8.2/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/scTE/miniglbase/genelist.py", line 1472, in load_list

    list_to_load[0]

IndexError: list index out of range

________________________________

**Comment by jphe** [comment]
We can not repeat your error, can you check the bed (6 columns) and gtf file format are correct?
