### ISSUE TITLE
error when run on test.bam

### ISSUE THREAD

**Issue by helianthuszhu** [JiekaiLab/scTE#19]
Hi there,
   Thanks for providing such wonderful  pipeline.
   I gave a try on the test.bam file in the Data folder, but got some error. Please check the details below.
   Two command lines two used: 
   scTE_build -g mm10
   scTE -i test.bam --min_genes 1 -o out.test -x mm10.exclusive.idx --hdf5 True -CB CR -UMI UR 
   And the log file got some error when 'Calculating expression':
######
INFO    : Parameter list:
Sample = out.test
Reference annotation index = mm10.exclusive.idx
Minimum number of genes required = 1
Minimum number of counts required = None
Number of threads = 1

INFO    : Loading the genome annotation index... 2021-07-14 13:43:59
INFO    : Loaded 'mm10.exclusive.idx' binary file with 3900779 items
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9', 'M', 'X', 'Y']
INFO    : Finished loading the genome annotation index... 2021-07-14 13:52:37
INFO    : Processing BAM/SAM files ...2021-07-14 13:52:37
INFO    : Input SAM/BAM file appears to be valid
CR UR good
INFO    : Done BAM/SAM files processing ...2021-07-14 13:52:52
INFO    : Splitting ...2021-07-14 13:52:52
INFO    : Executing single thread path
INFO    : Finished processing sample files 2021-07-14 13:52:52
INFO    : Fetching from the annotation index... 2021-07-14 13:52:52
INFO    : Done fetching... 2021-07-14 13:52:54
INFO    : Calculating expression... 2021-07-14 13:52:54
Traceback (most recent call last):
  File "/home/setup/zhu/biotools/miniconda3/bin/scTE", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
  File "/home/setup/zhu/biotools/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/setup/zhu/biotools/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/setup/zhu/biotools/miniconda3/lib/python3.7/site-packages/scTE-1.0-py3.7.egg/EGG-INFO/scripts/scTE", line 169, in <module>
    main()
  File "/home/setup/zhu/biotools/miniconda3/lib/python3.7/site-packages/scTE-1.0-py3.7.egg/EGG-INFO/scripts/scTE", line 155, in main
    len_res, genenumber, filename = Countexpression(filename=args.out, allelement=allelement, genenumber=args.genenumber, cellnumber=args.cellnumber, hdf5=args.hdf5)
  File "/home/setup/zhu/biotools/miniconda3/lib/python3.7/site-packages/scTE-1.0-py3.7.egg/scTE/base.py", line 505, in Countexpression
    adata = ad.AnnData(np.asarray(data),var = var,obs = obs)
  File "/home/setup/zhu/biotools/miniconda3/lib/python3.7/site-packages/anndata/_core/anndata.py", line 321, in __init__
    filemode=filemode,
  File "/home/setup/zhu/biotools/miniconda3/lib/python3.7/site-packages/anndata/_core/anndata.py", line 462, in _init_as_actual
    _check_2d_shape(X)
  File "/home/setup/zhu/biotools/miniconda3/lib/python3.7/site-packages/anndata/_core/anndata.py", line 97, in _check_2d_shape
    f"X needs to be 2-dimensional, not {len(X.shape)}-dimensional."
ValueError: X needs to be 2-dimensional, not 1-dimensional.
######
Do you have any suggestions on this error? 
Thank you very much!

**Comment by jphe** [comment]
the test.bam under scTE is extreamly small which only contain 1 cell. For h5ad, the data saved as sparse matrix which needs at least2 cells. You need to set --hdf5  False when the data only has 1 cell.

**Comment by helianthuszhu** [comment]
Oh, I see. I will try on some real data. Thank you very much!
