### ISSUE TITLE
KeyError: 'M'

### ISSUE THREAD

**Issue by Chris-lang478** [JiekaiLab/scTE#32]
Hi.

I am so confused about the  KeyError: 'M'. I've used it with the sam bam file, however, now it report the error.I tried few times and reinstall the git. The bug still exits.

DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
INFO    : Parameter list:
Sample = out
Reference annotation index = /home/data/xxxx/xxxxxx/scte/macFas5.exclusive.idx
Minimum number of genes required = 200
Minimum number of counts required = None
Number of threads = 1 

INFO    : Loading the genome annotation index... 2022-03-08 12:10:31
INFO    : Loaded '/home/data/xxxxx/xxxxx/scte/macFas5.exclusive.idx' binary file with 4428688 items
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '3', '4', '5', '6', '7', '8', '9', 'X']
INFO    : Finished loading the genome annotation index... 2022-03-08 12:11:28 

INFO    : Processing BAM/SAM files ...2022-03-08 12:11:28
INFO    : Input SAM/BAM file appears to be valid
CR UR good

INFO    : Done BAM/SAM files processing ...2022-03-08 13:26:22 

INFO    : Splitting ...2022-03-08 13:26:22
INFO    : Executing single thread path
Traceback (most recent call last):
  File "/home/data/xxxx/miniconda3/envs/xxxxxxx/bin/scTE", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
  File "/home/data/xx/miniconda3/envs/xxxxxx/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/data/xxx/miniconda3/envs/xxxxxx/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/data/xxx/miniconda3/envs/xxxxx/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTE", line 169, in <module>
    main()
  File "/home/data/xxxxx/miniconda3/envs/xxxxxx/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTE", line 129, in main
    whitelist = splitAllChrs(chr_list, filename=outname, genenumber=args.genenumber, countnumber=args.countnumber, UMI=args.UMI)
  File "/home/data/xxxxxxxx/miniconda3/envs/xxxxxx/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/scTE/base.py", line 260, in splitAllChrs
    if line in uniques[chrom]:
KeyError: 'M'

How can I  fix it?

Thanks and best wishes,
Chris

**Comment by LHXqwq** [comment]
I encountered the same issue, have you resolved it?

**Comment by LHXqwq** [comment]
cat keep_chrs.txt 
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
X
Y

samtools view -b old.bam $(cat keep_chrs.txt) > new.bam

Some reads in the bam file map to MT or contigs, removing these reads allows normal operation
