### ISSUE TITLE
ImportError: cannot import name 'Literal'

### ISSUE THREAD

**Issue by alfonsosaera** [JiekaiLab/scTE#40]
Hi jphe,

I am trying to use scTE but get the following error:

```
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/anndata-0.8.0-py3.6.egg/anndata/compat/__init__.py", line 65, in <module>
    from typing import Literal
ImportError: cannot import name 'Literal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scTE", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
  File "/home/asaera/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/asaera/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/scTE-1.0-py3.6.egg/EGG-INFO/scripts/scTE", line 13, in <module>
    from scTE.base import *
  File "/usr/local/lib/python3.6/dist-packages/scTE-1.0-py3.6.egg/scTE/base.py", line 16, in <module>
    import anndata as ad
  File "/usr/local/lib/python3.6/dist-packages/anndata-0.8.0-py3.6.egg/anndata/__init__.py", line 7, in <module>
    from ._core.anndata import AnnData
  File "/usr/local/lib/python3.6/dist-packages/anndata-0.8.0-py3.6.egg/anndata/_core/anndata.py", line 27, in <module>
    from .raw import Raw
  File "/usr/local/lib/python3.6/dist-packages/anndata-0.8.0-py3.6.egg/anndata/_core/raw.py", line 11, in <module>
    from .aligned_mapping import AxisArrays, AxisArraysView
  File "/usr/local/lib/python3.6/dist-packages/anndata-0.8.0-py3.6.egg/anndata/_core/aligned_mapping.py", line 11, in <module>
    from ..utils import deprecated, ensure_df_homogeneous
  File "/usr/local/lib/python3.6/dist-packages/anndata-0.8.0-py3.6.egg/anndata/utils.py", line 11, in <module>
    from ._core.sparse_dataset import SparseDataset
  File "/usr/local/lib/python3.6/dist-packages/anndata-0.8.0-py3.6.egg/anndata/_core/sparse_dataset.py", line 23, in <module>
    from ..compat import _read_attr
  File "/usr/local/lib/python3.6/dist-packages/anndata-0.8.0-py3.6.egg/anndata/compat/__init__.py", line 68, in <module>
    from typing_extensions import Literal
  File "/usr/local/lib/python3.6/dist-packages/typing_extensions-4.2.0-py3.6.egg/typing_extensions.py", line 159, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
```

The code for scTE is as follows

```
mainD='/media/path/to/folder/'
inF="${mainD}STARsolo/sample1/"
inBAM="${inF}Aligned.sortedByCoord.out.bam"
outDir="${mainD}scTE/sample1/"
mkdir -p $outDir
scTE -i $inBAM -o $outDir -x "${mainD}hg38.exclusive.idx" -CB CR -UMI UR
```

idx file was generated as follows
```
cd ${mainD}
scTE_build -g hg38
```

This is a 10X chromium V3 experiment and BAM file was generated with STARsolo, I can provide the code if you need it.

I made multiple test and I always get the same error as above. I tried parsing the BAM file to move Cell barcode and UMI from CR/UR to CB/UB, I tried using out for `-o` as in the manual, I tried with both `--hdf5 True` and `--hdf5 False` but always get the same error.

Any idea or advice would be highly appreciated.

Thanks,

**Comment by alfonsosaera** [comment]
It seems I could fix the issue, see https://github.com/jphe/scTE/issues/8#issuecomment-1197824704
