### ISSUE TITLE
scATAC:TypeError: align() got an unexpected keyword argument 'CB'

### ISSUE THREAD

**Issue by momo-FLY** [JiekaiLab/scTE#44]
Hi,

I ran scTEATAC with the following options, and it threw an IndexError. I am pasting the details below. Could you please help?
================
$python ./bin/scTEATAC -i CD_ICA.bam -x hg38.te.atac.idx -o out_atac
INFO    : Arguments:
INFO    : out: out_atac
INFO    : index: hg38.te.atac.idx 

INFO    : Minimum number of counts required = 1000
INFO    : Number of threads = 1 
INFO    : Loading the genome annotation index... 2022-10-07 17:43:47
INFO    : Loaded 'hg38.te.atac.idx' binary file with 4005310 items
INFO    : Finished loading the genome annotation index... 2022-10-07 17:44:27 

INFO    : Processing BAM/SAM files ...2022-10-07 17:44:27
*****WARNING: Query GTGTCAAAGGCAGTAC:150385822#0 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
(many warning)
*****WARNING: Query AGGACGATCGGTAGGA:188109048#0 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
INFO    : Done BAM/SAM files processing ...2022-10-07 17:55:22 

INFO    : Splitting ...2022-10-07 17:55:22
INFO    : Executing single thread path
INFO    : Finished processing sample files 2022-10-07 17:55:37 

INFO    : Fetching from the annotation index... 2022-10-07 17:55:37
Traceback (most recent call last):
  File "./bin/scTEATAC2", line 216, in <module>
    main()
  File "./bin/scTEATAC2", line 185, in main
    align(chr=chrom, filename=outname, all_annot=None, glannot=glannot, whitelist=whitelist, CB=args.CB)
TypeError: align() got an unexpected keyword argument 'CB'

================
We changed some code in scTEATAC for the following error:
'''
$python ./bin/scTEATAC -i CD_ICA.bam -x hg38.te.atac.idx -o out_atac                
usage: scTE_scatacseq [-h] [--ondisk] [--min_counts INT] [-CB [{True,False}]] [-UMI [{True,False}]]
                      [--ignoreDuplicates [{True,False}]] [--keeptmp [{True,False}]] [-p INT] [--hdf5 [{True,False}]] -i INPUT
                      [INPUT ...] -o [OUT] -x ANNOGLB [ANNOGLB ...] -g [genome]
scTE_scatacseq: error: the following arguments are required: -g/--genome
'''
delete 'genome=args.genome' in line 144
delete line93 and line 94

Thanks
Xia

**Comment by momo-FLY** [comment]
Hi, i got another error with scTEATAC
-------------------------------------------------
INFO    : Processing BAM/SAM files ...2022-11-01 22:32:03
Failed to open BAM file ../kidney_bam/ZY1/outs/test_bam.bam
INFO    : Done BAM/SAM files processing ...2022-11-01 22:32:03

INFO    : Splitting ...2022-11-01 22:32:03
INFO    : Executing single thread path
INFO    : Finished processing sample files 2022-11-01 22:32:04

INFO    : Fetching from the annotation index... 2022-11-01 22:32:04
INFO    : Done fetching... 2022-11-01 22:32:04

INFO    : Calculating expression... 2022-11-01 22:32:04
INFO    : Detect 0 cells expressed at least 0 genes, results output to test_bam.csv
INFO    : Finished calculating expression 2022-11-01 22:32:04
INFO    : Done with 0d 0h 0m 24s

Traceback (most recent call last):
  File "./bin/scTEATAC2", line 216, in <module>
    main()
  File "./bin/scTEATAC2", line 212, in main
    os.remove(tmpfilename)
NameError: name 'tmpfilename' is not defined
