### ISSUE TITLE
no hdf5 out

### ISSUE THREAD

**Issue by liuyuchenlab** [JiekaiLab/scTE#70]
hi i use this
 scTE -i possorted_genome_bam.bam -x /disk5/lyc/index/mouse/scte/mm39.exclusive.idx  --hdf5 True -CB CR -p 4 -o scte/
and there only have a scte.csv without the hdf5
Could you tell me how to fix it?
Thank you.

**Comment by jphe** [comment]
Can you provide more details with the scTE output log file?

**Comment by liuyuchenlab** [comment]
Traceback (most recent call last):
  File "/home/lyc/miniconda3/bin/scTE", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
  File "/home/lyc/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/lyc/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/lyc/miniconda3/lib/python3.9/site-packages/[scTE-1.0-py3.9.egg/EGG-INFO/scripts/scTE](http://scte-1.0-py3.9.egg/EGG-INFO/scripts/scTE)", line 173, in <module>
    main()
  File "/home/lyc/miniconda3/lib/python3.9/site-packages/[scTE-1.0-py3.9.egg/EGG-INFO/scripts/scTE](http://scte-1.0-py3.9.egg/EGG-INFO/scripts/scTE)", line 155, in main
    len_res, genenumber, filename = Countexpression(filename=args.out, allelement=allelement, genenumber=args.genenumber, cellnumber=args.cellnumber, hdf5=args.hdf5)
  File "/home/lyc/miniconda3/lib/python3.9/site-packages/[scTE-1.0-py3.9.egg/scTE/base.py](http://scte-1.0-py3.9.egg/scTE/base.py)", line 427, in Countexpression
    o = gzip.open('%s_scTEtmp/o4/%s.bed.gz'%(filename, filename), 'rt')
  File "/home/lyc/miniconda3/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/lyc/miniconda3/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/RNA_seq_1/lyc/project/lxm/scte/e14/e14_scTEtmp/o4//RNA_seq_1/lyc/project/lxm/scte/e14/e14.bed.gz'

**Comment by liuyuchenlab** [comment]
Sorry, I'm not very professional, will this help?

**Comment by EddieLv** [comment]
Perhaps u can try not using your own genome

**Comment by liuyuchenlab** [comment]
> Perhaps u can try not using your own genome

It looks like he can't export to other locations?Because the output to the current directory is successful。

**Comment by EddieLv** [comment]
Sorry, I misunderstood it before. I think your question is caused by your wrong parameter setting of [-o], which should not be ended with '/', because it should be prefix of the output filename.
![image](https://github.com/JiekaiLab/scTE/assets/61786787/953d5117-8b0b-468e-b38d-e2862230ed8b)
So you should set [-o scte/] to [-o scte] :)

**Comment by MF114** [comment]
Hi, I'm encountering the same issue, have you solved yet?

**Comment by liuyuchenlab** [comment]
> Hi, I'm encountering the same issue, have you solved yet?

yes,just put  the output to the current directory

**Comment by MF114** [comment]
> > Hi, I'm encountering the same issue, have you solved yet?
> 
> yes,just put the output to the current directory

Thanks~
