### ISSUE TITLE
depracation waring and filenotfounderror

### ISSUE THREAD

**Issue by Kiliankleemann** [JiekaiLab/scTE#73]
Hi I'm getting a deprication waring:
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7

The command then appears to run ok but then I'm getting the following:
Traceback (most recent call last):
  File "/home/kilian/anaconda3/envs/ONT_pipeline/bin/scTE", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
  File "/home/kilian/anaconda3/envs/ONT_pipeline/lib/python3.10/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kilian/anaconda3/envs/ONT_pipeline/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1561, in run_script
    exec(code, namespace, namespace)
  File "/home/kilian/anaconda3/envs/ONT_pipeline/lib/python3.10/site-packages/scTE-1.0-py3.10.egg/EGG-INFO/scripts/scTE", line 173, in <module>
    main()
  File "/home/kilian/anaconda3/envs/ONT_pipeline/lib/python3.10/site-packages/scTE-1.0-py3.10.egg/EGG-INFO/scripts/scTE", line 155, in main
    len_res, genenumber, filename = Countexpression(filename=args.out, allelement=allelement, genenumber=args.genenumber, cellnumber=args.cellnumber, hdf5=args.hdf5)
  File "/home/kilian/anaconda3/envs/ONT_pipeline/lib/python3.10/site-packages/scTE-1.0-py3.10.egg/scTE/base.py", line 427, in Countexpression
    o = gzip.open('%s_scTEtmp/o4/%s.bed.gz'%(filename, filename), 'rt')
  File "/home/kilian/anaconda3/envs/ONT_pipeline/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/kilian/anaconda3/envs/ONT_pipeline/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'scTE_out/SRR18609960_scTEtmp/o4/scTE_out/SRR18609960.bed.gz'

- Im running command on ubuntu 22.04 machine with python 3.11
- command: mkdir scTE_out
cat sample_list.txt | while read sample; do
	scTE -i alignments_STAR/${sample}Aligned.out.bam -o scTE_out/${sample} -x reference/hg38.exclusive.idx --hdf5 True -CB CR -UMI UR
done

**Comment by Ziyan-Lin** [comment]
Hi, I have the same issue. Have you solved it? Many thanks, Ziyan

**Comment by MF114** [comment]
Hi, I having the exact same issue. Have you solved it?

**Comment by shogohlab** [comment]
Hi, I also have the exact same issue. Have you solved it? @jphe
