### ISSUE TITLE
ValueError: Invalid Mode: uR

### ISSUE THREAD

**Issue by Kiliankleemann** [JiekaiLab/scTE#85]
Hello, 
I'm getting the following error: 

INFO: Processing BAM/SAM files ...2024-04-12 11:37:02
Traceback (most recent call last):
  File "/home/kilian/miniconda3/bin/scTE", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
  File "/home/kilian/miniconda3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kilian/miniconda3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1561, in run_script
    exec(code, namespace, namespace)
  File "/home/kilian/miniconda3/lib/python3.11/site-packages/scTE-1.0-py3.11.egg/EGG-INFO/scripts/scTE", line 173, in <module>
    main()
  File "/home/kilian/miniconda3/lib/python3.11/site-packages/scTE-1.0-py3.11.egg/EGG-INFO/scripts/scTE", line 109, in main
    checkCBUMI(filename=k,out=outname,CB=args.CB,UMI=args.UMI)
  File "/home/kilian/miniconda3/lib/python3.11/site-packages/scTE-1.0-py3.11.egg/scTE/base.py", line 113, in checkCBUMI
    o=open('%s_scTEtmp/o1/testCR.txt'%(out),'rU')
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

Not sure how to work around this - what I did wrong? 

Please see my starSolo Script: 
mkdir Alignment_EM
STAR --runMode alignReads \
	--soloType Droplet \
	--genomeDir /media/kilian/OS/STAR_index_hg38 \
	--readFilesIn fastq_files/APOE1/APOE1_S1_L001_R2_001.fastq.gz,fastq_files/APOE1/APOE1_S1_L002_R2_001.fastq.gz,fastq_files/APOE1/APOE1_S1_L003_R2_001.fastq.gz \
	fastq_files/APOE1/APOE1_S1_L001_R1_001.fastq.gz,fastq_files/APOE1/APOE1_S1_L002_R1_001.fastq.gz,fastq_files/APOE1/APOE1_S1_L003_R1_001.fastq.gz \
	--soloCBwhitelist /media/kilian/OS/STAR_reference_files/3M-february-2018.txt \
	--outSAMtype BAM Unsorted \
	--outSAMattributes NH HI AS nM CR CY UR UY \
	--readFilesCommand zcat \
	--outFilterMultimapNmax 100 \
	--winAnchorMultimapNmax 100 \
	--outMultimapperOrder Random \
	--runRNGseed 777 \
	--outSAMmultNmax 1 \
	--twopassMode Basic \
	--soloUMIlen 10 \
	--soloMultiMappers EM \
	--runThreadN 16 \
	--outFileNamePrefix Alignment_EM/APOE1_S1 \
	--outReadsUnmapped Fastx \
	--outSAMunmapped Within \
	--soloBarcodeReadLength 0

And the alignment summary: 
Number of Reads,25400926
Reads With Valid Barcodes,0.980799
Sequencing Saturation,0.150308
Q30 Bases in CB+UMI,0.962055
Q30 Bases in RNA read,0.923963
Reads Mapped to Genome: Unique+Multiple,0.909326
Reads Mapped to Genome: Unique,0.797794
Reads Mapped to Gene: Unique+Multiple Gene,0.203119
Reads Mapped to Gene: Unique Gene,0.18643
Estimated Number of Cells,3893
Unique Reads in Cells Mapped to Gene,2640997
Fraction of Unique Reads in Cells,0.557703
Mean Reads per Cell,678
Median Reads per Cell,605
UMIs in Cells,2232977
Mean UMI per Cell,573
Median UMI per Cell,512
Mean Gene per Cell,329
Median Gene per Cell,292
Total Gene Detected,18279

I would greatly appreciate advice and help :)

**Comment by jphe** [comment]
The U file mode was removed in Python 3.11. I'll fix scTE later, you can run with python 3.10 or older

**Comment by jphe** [comment]
have fixed this problem, can you reinstall it and try again?

**Comment by Kiliankleemann** [comment]
Ill try today - Will let you know.

**Comment by shogohlab** [comment]
Has this been fixed so that scTE can run using Python3.13? Unfortunately, I encountered a separate problem with running scTE on v3.10

**Comment by PeterWang0502** [comment]
I encountered a similar problem `ValueError: invalid mode: 'rU'` when running **scTE_build** on T2T genome under Python 3.13.5. I was able to solve it by changing `o = open(tefile,'rU')` to `o = open(tefile,'r')` in **scTE_build** as suggested in #54.
